version: '3.1'

services:

    neo4j:
        image: neo4j:2.3
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        volumes:
            - ./data:/data
        ports:
            - 7474:7474
