version: '3.1'

services:

    neo4j:
        image: neo4j:3.3
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        volumes:
            - ./data:/data
            - ./import:/import
        ports:
            - 7474:7474
            - 7687:7687
