# Use postgres/example user/password credentials
version: '3.1'

services:

    db:
        image: postgres:9.6
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        environment:
            POSTGRES_PASSWORD: example
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./data:/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432

    adminer:
        image: adminer
        ports:
            - 8080:8080
